title = "@mjbright Consulting - XXXX Labs"
#baseURL = "https://example.com"
baseURL = "/"
languageCode = "en-us"

# https://github.com/theNewDynamic/gohugo-theme-ananke
theme = "ananke"
themesDir = "themes"

# To allow raw-html: uncomment
[markup.goldmark.renderer]
unsafe=true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
Paginate = 6
googleAnalytics = ""
#enableRobotsTXT = true
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# See https://gohugo.io/hugo-modules/configuration/#module-configuration-mounts
# EXCLUDE AWS Content:
[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = 'aws/*'

[[menu.main]]
    name = "[XXX] Labs"
    source = "content"
    target = "content/default"
    url = "/default/"
    #url = "/tf-labs/"
    weight = 2

[params]
  favicon = ""
  description = "@mjbright Consulting - XXXX Labs."
  facebook = ""
  twitter = "https://twitter.com/mjbright"
  instagram = ""
  youtube = ""
  github = "https://github.com/mjbright"
  linkedin = "https://www.linkedin.com/in/mjbright"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = "bg-black"
  #background_color_class = "bg-blue"
  background_color_class = "bg-purple"
  featured_image = "/images/LOGO.png"
  recent_posts_number = 2
  #date_format = "2. January 2006"
  date_format = ":date_full"
  time_format = ":time_full"
  custom_css = ["mjbrightC-tf.css"]
  #custom_css = ["mjbrightC-k8s.css"]
